name: publish
on:
    workflow_dispatch:
    push:
        branches:
            - publish
jobs:
    publish:
        runs-on: ubuntu-latest
        environment: publish
        steps:
            - uses: actions/checkout@v2
            - run: yarn
            - run: yarn build
            - run: yarn config set npmAuthToken $NPM_AUTH_TOKEN
              env:
                  NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
            - run: yarn config set npmAlwaysAuth true
            - run: yarn npm publish
              working-directory: library
